"""
validator.py

Validates the JSON generated by the LLM against the job schema.
"""

from pathlib import Path
from typing import Any

from jsonschema import validate, ValidationError

from modules.utils import load_json


class SchemaValidator:
    """
    Validates JSON data using a JSON Schema.
    """

    def __init__(self, schema_file: Path) -> None:
        """
        Parameters
        ----------
        schema_file : Path
            Path to the JSON schema.
        """
        self.schema = load_json(schema_file)

    def validate(self, data: dict[str, Any]) -> bool:
        """
        Validate JSON data.

        Parameters
        ----------
        data : dict

        Returns
        -------
        bool

        Raises
        ------
        ValidationError
            If the JSON does not comply with the schema.
        """

        validate(
            instance=data,
            schema=self.schema
        )

        return True